[package]
name = "todo-rs"
version = "0.1.0"
authors = ["thinegen <git@thinegen.de>"]
edition = "2018"

[dependencies]
ansi_term = "0.12"
home = "0.5.3"

[dependencies.tabwriter]
version = "1.2.1"
features=["ansi_formatting"]